blank_issues_enabled: false
contact_links:
  - name: TWL Mode Hacking Discord Server
    url:
    about: "Please use the #support Discord Server to ask for support-related questions, such as needing assistance to launch TWiLight Menu++"
  - name: nds-bootstrap Github Repository
    url: https://github.com/ahezard/nds-bootstrap/issues/new
    about: Please use this Github Repository to report issues related to running Nintendo DS applications as `.nds` files (not as a retail cart) via B4DS/nds-bootstrap (and not via Flashcarts, if your flashcart supports that)
  - name: GBARunner2 Github Repository
    url: https://github.com/Gericom/GBARunner2/issues/new
    about: Please use this Github Repository to report issues related to running GameBoy Advance applications as `.gba` files (not as Slot-2 for DS Phat/Lite consoles), or the GBARunner2 GUI
  - name: MPEG4Player/YouTubeDS Github Repository
    url: https://github.com/Gericom/YouTubeDS/issues/new
    about: Please use this Github Repository to report issues related to .mp4 playback
